env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/jsx-runtime"
  # - "plugin:jest-dom/recommended"
  # - "plugin:testing-library/react"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - "react-hooks"
  # - "jest-dom"
  # - testing-library
rules: {
    "react-hooks/rules-of-hooks": "error", # Checks rules of Hooks
    "react-hooks/exhaustive-deps": "warn", # Checks effect dependencies
    "@typescript-eslint/ban-ts-comment": "off",
    "react/prop-types": "off",
    "@typescript-eslint/no-empty-function": "off",
    "@typescript-eslint/no-unused-vars": ["warn", { "argsIgnorePattern": "^_" }],
    "@typescript-eslint/no-explicit-any": "off"
  }
settings:
  react:
    version: detect
